language: groovy
jdk:
  - oraclejdk7
branches:
  only:
    - master
    - test
script: ./grailsw refresh-dependencies
  && ./grailsw test-app -coverage -xml
  && ./grailsw refresh-dependencies
  && ./grailsw "test-app functional:"
after_success:
    - ./grailsw coveralls
